# Comment to a new issue.
issuesOpened: >
  Hi there 👋,
  Issues are only for reporting a Bug/Feature request. For limited support, questions, and discussions,
  please join MobSF Slack channel: http://tiny.cc/mobsf

  Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.

pullRequestOpened: >
  Thank you for your pull request. ❤

  Please make sure you have followed our contribution guidelines. We will review it as soon as possible.
